resources:
  schemas:
      landing:
        catalog_name: ${var.catalog}
        name: landing
        comment: "Landing schema"

      system:
        catalog_name: ${var.catalog}
        name: system
        comment: "system schema"
      
      bronze:
        catalog_name: ${var.catalog}
        name: bronze
        comment: "Bronze schema for raw data"
      
      silver:
        catalog_name: ${var.catalog}
        name: silver
        comment: "Silver schema for cleaned data"
      
      gold:
        catalog_name: ${var.catalog}
        name: gold
        comment: "Gold schema for aggregated data"
      
      snapshots:
        catalog_name: ${var.catalog}
        name: snapshots
        comment: "Snapshots schema for historical data"